# Generated by Django 4.2.7 on 2026-01-21 04:41

import api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.get_organization_image_path, verbose_name='image')),
                ('style', models.CharField(blank=True, default='', max_length=255, verbose_name='style')),
                ('state', models.CharField(choices=[('publish', 'publish'), ('pending', 'pending'), ('private', 'private'), ('draft', 'draft')], default='publish', max_length=255, verbose_name='state')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='order')),
                ('virtual', models.BooleanField(default=False, verbose_name='virtual')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(blank=True, help_text='Código único para identificar el catálogo (ej: CAT001, VERANO2026)', max_length=50, null=True, verbose_name='code')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el catálogo está activo', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'catalogue',
                'verbose_name_plural': 'catalogues',
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.get_organization_image_path, verbose_name='image')),
                ('style', models.CharField(blank=True, default='', max_length=255, verbose_name='style')),
                ('state', models.CharField(choices=[('publish', 'publish'), ('pending', 'pending'), ('private', 'private'), ('draft', 'draft')], default='publish', max_length=255, verbose_name='state')),
                ('icon_file', models.ImageField(blank=True, null=True, upload_to=api.models.get_organization_icon_path, verbose_name='icon file')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='order')),
                ('virtual', models.BooleanField(default=False, verbose_name='virtual')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='code')),
                ('image', models.ImageField(upload_to=api.models.get_organization_image_path, verbose_name='image')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.get_organization_image_path, verbose_name='image')),
                ('style', models.CharField(blank=True, default='', max_length=255, verbose_name='style')),
                ('state', models.CharField(choices=[('publish', 'publish'), ('pending', 'pending'), ('private', 'private'), ('draft', 'draft')], default='publish', max_length=255, verbose_name='state')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='order')),
                ('virtual', models.BooleanField(default=False, verbose_name='virtual')),
                ('catalogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='api.catalogue', verbose_name='catalogue')),
                ('images', models.ManyToManyField(blank=True, to='api.images', verbose_name='images')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.slide', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slides',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.get_organization_image_path, verbose_name='image')),
                ('style', models.CharField(blank=True, default='', max_length=255, verbose_name='style')),
                ('state', models.CharField(choices=[('publish', 'publish'), ('pending', 'pending'), ('private', 'private'), ('draft', 'draft')], default='publish', max_length=255, verbose_name='state')),
                ('length', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12, null=True, verbose_name='length')),
                ('width', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12, null=True, verbose_name='width')),
                ('height', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12, null=True, verbose_name='height')),
                ('sku', models.CharField(blank=True, max_length=250, null=True, verbose_name='sku')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='short description')),
                ('currency', models.CharField(blank=True, choices=[('CLP', 'Peso Chileno (CLP)'), ('PEN', 'Sol (PEN)')], max_length=10, null=True, verbose_name='currency')),
                ('price_1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price 1')),
                ('price_2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price 2')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='weight')),
                ('manage_stock', models.BooleanField(default=False, verbose_name='manage stock')),
                ('stock_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='stock quantity')),
                ('stock_status', models.CharField(choices=[('instock', 'instock'), ('outofstock', 'outofstock'), ('onbackorder', 'onbackorder')], default='instock', max_length=20, verbose_name='stock status')),
                ('virtual', models.BooleanField(default=False, verbose_name='virtual')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.brand', verbose_name='brand')),
                ('catalogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.catalogue', verbose_name='catalogue')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='api.category', verbose_name='categories')),
                ('images', models.ManyToManyField(blank=True, to='api.images', verbose_name='images')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='api.product', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created'],
                'unique_together': {('sku', 'catalogue')},
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='meta keywords')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='api.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'meta data',
                'verbose_name_plural': 'meta data',
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='imports/', verbose_name='file')),
                ('images_zip', models.FileField(blank=True, null=True, upload_to='imports/zips/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='images zip')),
                ('currency', models.CharField(blank=True, choices=[('CLP', 'Peso Chileno (CLP)'), ('PEN', 'Sol (PEN)')], max_length=10, null=True, verbose_name='currency')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('uploaded', models.BooleanField(default=False, verbose_name='uploaded')),
                ('import_mode', models.CharField(choices=[('update', 'Actualizar existentes y crear nuevos'), ('create_only', 'Solo crear nuevos (no actualizar)'), ('replace_all', 'Reemplazar todo (eliminar y recrear)'), ('soft_delete', 'Sincronizar (ocultar no incluidos)')], default='soft_delete', help_text='Modo de importación: update (actualiza y crea), create_only (solo nuevos), replace_all (elimina todo), soft_delete (oculta no incluidos)', max_length=20, verbose_name='import mode')),
                ('catalogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_files', to='api.catalogue', verbose_name='catalogue')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_files', to=settings.AUTH_USER_MODEL, verbose_name='user created')),
            ],
            options={
                'verbose_name': 'import file',
                'verbose_name_plural': 'import files',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='images',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization', verbose_name='organization'),
        ),
        migrations.CreateModel(
            name='ClientConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Nombre del cliente', max_length=100, unique=True, verbose_name='client name')),
                ('organization_id', models.IntegerField(help_text='ID único para la organización (legacy)', unique=True, verbose_name='organization id')),
                ('primary_color', models.CharField(default='#FFFFFF', help_text='Color principal en formato hexadecimal, ej. #FF5733', max_length=7, verbose_name='primary color')),
                ('secondary_color', models.CharField(default='#000000', help_text='Color secundario en formato hexadecimal', max_length=7, verbose_name='secondary color')),
                ('accent_color', models.CharField(blank=True, default='#007BFF', help_text='Color de acento en formato hexadecimal', max_length=7, null=True, verbose_name='accent color')),
                ('logo', models.ImageField(blank=True, help_text='Logo del cliente', null=True, upload_to='client_configs/logos/', verbose_name='logo')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon del cliente', null=True, upload_to='client_configs/favicons/', verbose_name='favicon')),
                ('domain', models.CharField(help_text='Dominio o subdominio del cliente (ej. cliente.dominio.com)', max_length=255, unique=True, verbose_name='domain')),
                ('description', models.TextField(blank=True, help_text='Descripción del cliente', null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la configuración está activa', verbose_name='is active')),
                ('catalogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_configurations', to='api.catalogue', verbose_name='catalogue')),
            ],
            options={
                'verbose_name': 'client configuration',
                'verbose_name_plural': 'client configurations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.images', verbose_name='images'),
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.category', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogues', to='api.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='brand',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.images', verbose_name='images'),
        ),
        migrations.AddField(
            model_name='brand',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='brand',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.brand', verbose_name='parent'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogue',
            unique_together={('code', 'organization'), ('slug', 'organization')},
        ),
    ]
