# Generated by Django 4.2.7 on 2025-07-17 23:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[('CLP', 'Peso Chileno (CLP)'), ('PEN', 'Sol (PEN)')], max_length=10, null=True, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12, null=True, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12, null=True, verbose_name='length'),
        ),
        migrations.AddField(
            model_name='product',
            name='manage_stock',
            field=models.BooleanField(default=False, verbose_name='manage stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='api.product', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='price 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='sku'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('publish', 'publish'), ('pending', 'pending'), ('private', 'private'), ('draft', 'draft')], default='publish', max_length=255, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='stock quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('instock', 'instock'), ('outofstock', 'outofstock'), ('onbackorder', 'onbackorder')], default='instock', max_length=20, verbose_name='stock status'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='style'),
        ),
        migrations.AddField(
            model_name='product',
            name='virtual',
            field=models.BooleanField(default=False, verbose_name='virtual'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=12, null=True, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='meta keywords')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='api.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'meta data',
                'verbose_name_plural': 'meta data',
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='imports/', verbose_name='file')),
                ('images_zip', models.FileField(blank=True, null=True, upload_to='imports/zips/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='images zip')),
                ('currency', models.CharField(blank=True, choices=[('CLP', 'Peso Chileno (CLP)'), ('PEN', 'Sol (PEN)')], max_length=10, null=True, verbose_name='currency')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('uploaded', models.BooleanField(default=False, verbose_name='uploaded')),
                ('remove_all', models.BooleanField(default=False, verbose_name='remove all')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization', verbose_name='organization')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_files', to=settings.AUTH_USER_MODEL, verbose_name='user created')),
            ],
            options={
                'verbose_name': 'import file',
                'verbose_name_plural': 'import files',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='code')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image')),
                ('style', models.CharField(blank=True, default='', max_length=255, verbose_name='style')),
                ('state', models.CharField(choices=[('publish', 'publish'), ('pending', 'pending'), ('private', 'private'), ('draft', 'draft')], default='publish', max_length=255, verbose_name='state')),
                ('icon_file', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='icon file')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='order')),
                ('virtual', models.BooleanField(default=False, verbose_name='virtual')),
                ('images', models.ManyToManyField(blank=True, to='api.images', verbose_name='images')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization', verbose_name='organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image')),
                ('style', models.CharField(blank=True, default='', max_length=255, verbose_name='style')),
                ('state', models.CharField(choices=[('publish', 'publish'), ('pending', 'pending'), ('private', 'private'), ('draft', 'draft')], default='publish', max_length=255, verbose_name='state')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='order')),
                ('virtual', models.BooleanField(default=False, verbose_name='virtual')),
                ('images', models.ManyToManyField(blank=True, to='api.images', verbose_name='images')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization', verbose_name='organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.brand', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.brand', verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.category', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.images', verbose_name='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization', verbose_name='organization'),
        ),
    ]
