# Generated by Django 4.2.7 on 2026-01-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='currency',
            field=models.CharField(blank=True, choices=[('CLP', 'Peso Chileno (CLP)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('ARS', 'Peso Argentino (ARS)'), ('BRL', 'Real Brasileño (BRL)'), ('MXN', 'Peso Mexicano (MXN)'), ('COP', 'Peso Colombiano (COP)'), ('PEN', 'Sol Peruano (PEN)')], default='CLP', max_length=10, null=True, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='currency',
            field=models.CharField(blank=True, choices=[('CLP', 'Peso Chileno (CLP)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('ARS', 'Peso Argentino (ARS)'), ('BRL', 'Real Brasileño (BRL)'), ('MXN', 'Peso Mexicano (MXN)'), ('COP', 'Peso Colombiano (COP)'), ('PEN', 'Sol Peruano (PEN)')], default='CLP', max_length=10, null=True, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[('CLP', 'Peso Chileno (CLP)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('ARS', 'Peso Argentino (ARS)'), ('BRL', 'Real Brasileño (BRL)'), ('MXN', 'Peso Mexicano (MXN)'), ('COP', 'Peso Colombiano (COP)'), ('PEN', 'Sol Peruano (PEN)')], max_length=10, null=True, verbose_name='currency'),
        ),
    ]
