# Generated by Django 4.2.7 on 2026-01-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_catalogue_currency_alter_importfile_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientconfiguration',
            name='organization_id',
        ),
        migrations.AddField(
            model_name='clientconfiguration',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', null=True, verbose_name='metadata'),
        ),
    ]
