# Generated by Django 4.2.7 on 2025-07-17 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organization_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image')),
                ('style', models.CharField(blank=True, default='', max_length=255, verbose_name='style')),
                ('state', models.CharField(choices=[('publish', 'publish'), ('pending', 'pending'), ('private', 'private'), ('draft', 'draft')], default='publish', max_length=255, verbose_name='state')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='order')),
                ('virtual', models.BooleanField(default=False, verbose_name='virtual')),
                ('images', models.ManyToManyField(blank=True, to='api.images', verbose_name='images')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization', verbose_name='organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.slide', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slides',
            },
        ),
    ]
