# Generated by Django 4.2.7 on 2025-09-29 16:13

import api.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Nombre del cliente', max_length=100, unique=True, verbose_name='client name')),
                ('organization_id', models.IntegerField(help_text='ID único para la organización', unique=True, verbose_name='organization id')),
                ('primary_color', models.CharField(default='#FFFFFF', help_text='Color principal en formato hexadecimal, ej. #FF5733', max_length=7, verbose_name='primary color')),
                ('secondary_color', models.CharField(default='#000000', help_text='Color secundario en formato hexadecimal', max_length=7, verbose_name='secondary color')),
                ('accent_color', models.CharField(blank=True, default='#007BFF', help_text='Color de acento en formato hexadecimal', max_length=7, null=True, verbose_name='accent color')),
                ('logo', models.ImageField(blank=True, help_text='Logo del cliente', null=True, upload_to='client_configs/logos/', verbose_name='logo')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon del cliente', null=True, upload_to='client_configs/favicons/', verbose_name='favicon')),
                ('domain', models.CharField(help_text='Dominio o subdominio del cliente (ej. cliente.dominio.com)', max_length=255, unique=True, verbose_name='domain')),
                ('description', models.TextField(blank=True, help_text='Descripción del cliente', null=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la configuración está activa', verbose_name='is active')),
            ],
            options={
                'verbose_name': 'client configuration',
                'verbose_name_plural': 'client configurations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_organization_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_file',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_organization_icon_path, verbose_name='icon file'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_organization_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=api.models.get_organization_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_organization_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_organization_image_path, verbose_name='image'),
        ),
    ]
