# Generated by Django 4.2.7 on 2026-01-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_clientconfiguration_organization_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='tags',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por comas (ej: bebida, vino, líquidos)', max_length=500, null=True, verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por comas (ej: bebida, vino, líquidos)', max_length=500, null=True, verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por comas (ej: bebida, vino, líquidos)', max_length=500, null=True, verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='slide',
            name='tags',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por comas (ej: bebida, vino, líquidos)', max_length=500, null=True, verbose_name='tags'),
        ),
    ]
