# Generated by Django 4.2.7 on 2026-01-22 03:59

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_brand_tags_category_tags_product_tags_slide_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.get_organization_image_path, verbose_name='image')),
                ('style', models.CharField(blank=True, default='', max_length=255, verbose_name='style')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas (ej: bebida, vino, líquidos)', max_length=500, null=True, verbose_name='tags')),
                ('state', models.CharField(choices=[('publish', 'publish'), ('pending', 'pending'), ('private', 'private'), ('draft', 'draft')], default='publish', max_length=255, verbose_name='state')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización de la playlist', verbose_name='order')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la playlist está activa', verbose_name='is active')),
                ('duration', models.IntegerField(blank=True, default=0, help_text='Duración total en segundos (calculado automáticamente)', null=True, verbose_name='duration')),
                ('images', models.ManyToManyField(blank=True, to='api.images', verbose_name='images')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'playlist',
                'verbose_name_plural': 'playlists',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='importfile',
            name='import_mode',
            field=models.CharField(choices=[('update', 'Actualizar existentes y crear nuevos'), ('create_only', 'Solo crear nuevos (no actualizar)'), ('replace_all', 'Reemplazar todo (eliminar y recrear)'), ('soft_delete', 'Sincronizar (ocultar no incluidos)')], default='update', help_text='Modo de importación: update (actualiza y crea), create_only (solo nuevos), replace_all (elimina todo), soft_delete (oculta no incluidos)', max_length=20, verbose_name='import mode'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('file', models.FileField(help_text='Formatos soportados: MP4, AVI, MOV, WMV, FLV, MKV, WEBM, M4V', upload_to=api.models.get_organization_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'mkv', 'webm', 'm4v'])], verbose_name='video file')),
                ('thumbnail', models.ImageField(blank=True, help_text='Miniatura del video', null=True, upload_to=api.models.get_organization_image_path, verbose_name='thumbnail')),
                ('orientation', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', help_text='Orientación del video', max_length=20, verbose_name='orientation')),
                ('duration', models.IntegerField(blank=True, default=0, help_text='Duración del video en segundos', null=True, verbose_name='duration')),
                ('order', models.IntegerField(default=0, help_text='Orden del video en la playlist', verbose_name='order')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el video está activo', verbose_name='is active')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization', verbose_name='organization')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.playlist', verbose_name='playlist')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['playlist', 'order', 'name'],
            },
        ),
    ]
