# Generated by Django 4.2.7 on 2026-01-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_playlist_alter_importfile_import_mode_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, help_text='Si se deja vacío, se usará el nombre del archivo', max_length=250, verbose_name='name'),
        ),
    ]
