# Generated by Django 4.2.7 on 2026-01-22 04:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_video_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['name'], 'verbose_name': 'playlist', 'verbose_name_plural': 'playlists'},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='order',
        ),
        migrations.CreateModel(
            name='CataloguePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(help_text='Fecha y hora de inicio de vigencia', verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Fecha y hora de fin de vigencia (opcional, sin fin si está vacío)', null=True, verbose_name='end date')),
                ('order', models.IntegerField(default=0, help_text='Orden de reproducción en el catálogo', verbose_name='order')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la asignación está activa', verbose_name='is active')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_playlists', to='api.catalogue', verbose_name='catalogue')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_assignments', to='api.playlist', verbose_name='playlist')),
            ],
            options={
                'verbose_name': 'catalogue playlist',
                'verbose_name_plural': 'catalogue playlists',
                'ordering': ['catalogue', 'order', 'start_date'],
                'unique_together': {('catalogue', 'playlist', 'start_date')},
            },
        ),
    ]
