# Generated by Django 4.2.7 on 2026-01-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_playlist_options_remove_playlist_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueplaylist',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de inicio de vigencia (opcional, vigente desde ahora si está vacío)', null=True, verbose_name='start date'),
        ),
    ]
