# Generated by Django 4.2.7 on 2026-05-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_clientconfiguration_theme_version'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='api_order_catalog_0bb97f_idx',
            old_name='api_order_catalog_e6d9c5_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='api_order_authori_a10e7d_idx',
            old_name='api_order_authori_8c98ad_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='api_order_termina_546adf_idx',
            old_name='api_order_termina_4f8b3c_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
