# Generated by Django 4.2.7 on 2026-05-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_clientconfiguration_upsell_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='attention_message',
            field=models.TextField(blank=True, help_text='Motivo de la alerta reportado por el totem.', null=True, verbose_name='attention message'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='attention_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='attention requested at'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='attention_required',
            field=models.BooleanField(default=False, help_text='True cuando el totem necesita ayuda humana.', verbose_name='attention required'),
        ),
    ]
