# Generated by Django 4.2.7 on 2026-05-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_terminal_attention_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='attention_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo un admin vio la alerta (paso intermedio antes de resolver).', null=True, verbose_name='attention acknowledged at'),
        ),
    ]
